import "./globals.css";
import Nav from "./components/Header/Nav";
import Footer from "./components/Footer/Footer";
import StoreDataProvider from "./store/StoreContext";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      <StoreDataProvider>
        <Nav/>
        {children}
        <Footer/>
        </StoreDataProvider>
      </body>
    </html>
  );
}
